export const SET_ALL_VIDEOGAMES = "SET_ALL_VIDEOGAMES";
export const SET_VIDEOGAME = "SET_VIDEOGAME";
export const SET_GENRES = "SET_GENRES";
export const SET_INFO_FILTER = "SET_INFO_FILTER";
export const SET_FILTER_VIDEOGAME = "SET_FILTER_VIDEOGAME";
export const SET_WHAT_RENDER = "SET_WHAT_RENDER";
export const SET_SLICE_VIDEOGAMES = "SET_SLICE_VIDEOGAMES";
export const SET_INPUT_ORDER = "SET_INPUT_ORDER";
export const ORDER_ALL_VIDEOGAMES = "ORDER_ALL_VIDEOGAMES";
export const ORDER_FILTER_VIDEOGAME = "ORDER_FILTER_VIDEOGAME";
export const ORDER_FILTER_CLICK = "ORDER_FILTER_CLICK";
export const SET_DETAIL_VIDEOGAME = "SET_DETAIL_VIDEOGAME";

export const URL_VIDEOGAMES = "/videogames";
export const URL_GENRES = "/genres";

export const SET_FLAG_GENRES = "SET_FLAG_GENRES";
export const SET_FLAG_EXISTS = "SET_FLAG_EXISTS";
